GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcmUiLCJpZCI6IjY1ZTMwOWM2N2RhMjZlNmU0MTE5M2YyOSIsImlhdCI6MTcwOTM4MzI4MSwiZXhwIjoxNzA5Mzg1MDgxfQ._3XOW38BdvtT2GBILVggQ9AWFRPFXSM9bHZDvx_Pp9E